insert into ref_refgroup(refgroupid, parentgroupid, groupname, groupsysname, description) values
(1, 0, 'ref group name 1', 'refgroupsysname1', 'description 1'),
(2, 1, 'ref group name 2', 'refgroupsysname2', 'description 2'),
(3, 1, 'ref group name 3', 'refgroupsysname3', 'description 3'),
(4, 1, 'ref group name 4', 'refgroupsysname4', 'description 4'),
(5, 1, 'ref group name 5', 'refgroupsysname5', 'description 5'),
(6, 0, 'ref group name 6', 'refgroupsysname6', 'description 6'),
(7, 6, 'ref group name 7', 'refgroupsysname7', 'description 7'),
(8, 6, 'ref group name 8', 'refgroupsysname8', 'description 8'),
(9, 6, 'ref group name 9', 'refgroupsysname9', 'description 9'),
(10, 6, 'ref group name 10', 'refgroupsysname10', 'description 10'),
(11, 0, 'ref group name 11', 'refgroupsysname11', 'description 11'),
(12, 11, 'ref group name 12', 'refgroupsysname12', 'description 12'),
(13, 11, 'ref group name 13', 'refgroupsysname13', 'description 13'),
(14, 11, 'ref group name 14', 'refgroupsysname14', 'description 14'),
(15, 11, 'ref group name 15', 'refgroupsysname15', 'description 15');