package ru.otus.homework.exceptions;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Errors {
    REQUIRED_PARAM(1, "%s"),
    REFERENCE_SYSNAME_IS_NULL(2, "%s"),
    REFERENCE_ID_AND_REFERENCE_SYSNAME_IS_NULL(3, "%s"),
    REFERENCE_GROUP_ID_IS_NULL(3, "%s"),
    VEHICLE_BRAND_ID_IS_NULL(4, "%s"),
    VEHICLE_MODEL_KIND_ID_IS_NULL(5, "%s"),
    VEHICLE_MODEL_ID_IS_NULL(6, "%s"),
    VEHICLE_SET_ID_IS_NULL(7, "%s"),

    NOT_UNIQUE_REFERENCE_GROUP_SYSNAME(100, "%s"),
    REFERENCE_GROUP_NOT_FOUND_BY_ID(101, "%s"),
    PARENT_REFERENCE_GROUP_NOT_FOUND_BY_ID(102, "%s"),
    REFERENCE_GROUP_HAS_CHILDREN_GROUPS(103, "%s"),
    REFERENCE_GROUP_HAS_LINKED_REFERENCES(104, "%s"),
    REFERENCE_GROUP_LIST_IS_EMPTY(105, "%s"),
    REFERENCE_GROUP_DUPLICATED_PARENTID_AND_SYSNAME(106, "%s"),

    NOT_UNIQUE_REFERENCE_SYSNAME(200, "%s"),
    REFERENCE_NOT_FOUND_BY_ID(201, "%s"),
    REFERENCE_LIST_IS_EMPTY(203, "%s"),
    REFERENCE_DUPLICATED_SYSNAME(204, "%s"),
    REFERENCE_NOT_FOUND_BY_SYSNAME(205, "%s"),

    NOT_UNIQUE_REFERENCE_ITEM_CODE(300, "%s"),
    REFERENCE_ITEM_NOT_FOUND_BY_ID(301, "%s"),
    REFERENCE_ITEM_NOT_FOUND_BY_REFERENCEID_AND_CODE(302, "%s"),
    REFERENCE_ITEM_LIST_IS_EMPTY(303, "%s"),
    REFERENCE_ITEM_DUPLICATED_REFERENCEID_AND_CODE(304, "%s"),

    NOT_UNIQUE_ROLE_SYSNAME(400, "%s"),
    ROLE_NOT_FOUND_BY_ID(401, "%s"),
    ROLE_LIST_IS_EMPTY(402, "%s"),
    ROLE_DUPLICATED_SYSNAME(403, "%s"),

    NOT_UNIQUE_BRAND_NAME(500, "%s"),
    PRODUCTION_TYPE_NOT_FOUND_BY_ID(501, "%s"),
    INVALID_PRODUCTION_TYPE_REFERENCE(502, "%s"),
    VEHICLE_BRAND_NOT_FOUND_BY_ID(503, "%s"),
    VEHICLE_BRAND_LIST_IS_EMPTY(504, "%s"),
    VEHICLE_BRAND_DUPLICATED_NAME(505, "%s"),
    VEHICLE_BRAND_DUPLICATED_ID(506, "%s"),

    NOT_UNIQUE_MODEL_NAME(600, "%s"),
    VEHICLE_KIND_NOT_FOUND_BY_ID(601, "%s"),
    INVALID_VEHICLE_KIND_REFERENCE(602, "%s"),
    VEHICLE_MODEL_NOT_FOUND_BY_ID(603, "%s"),
    PROPERTY_FORM_NOT_FOUND_BY_ID(604, "%s"),
    INVALID_PROPERTY_FORM_REFERENCE(605, "%s"),
    VEHICLE_MODEL_LIST_IS_EMPTY(606, "%s"),
    VEHICLE_MODEL_DUPLICATED_NAME(607, "%s"),

    VEHICLE_SET_NOT_FOUND_BY_ID(700, "%s"),
    VEHICLE_BODY_NOT_FOUND_BY_ID(701, "%s"),
    INVALID_VEHICLE_BODY_REFERENCE(702, "%s"),
    VEHICLE_ENGINE_SIZE_NOT_FOUND_BY_ID(703, "%s"),
    INVALID_VEHICLE_ENGINE_SIZE_REFERENCE(704, "%s"),
    VEHICLE_ENGINE_TYPE_NOT_FOUND_BY_ID(705, "%s"),
    INVALID_VEHICLE_ENGINE_TYPE_REFERENCE(706, "%s"),
    VEHICLE_ENGINE_POWER_NOT_FOUND_BY_ID(707, "%s"),
    INVALID_VEHICLE_ENGINE_POWER_REFERENCE(708, "%s"),
    VEHICLE_TRANSMISSION_NOT_FOUND_BY_ID(709, "%s"),
    INVALID_VEHICLE_TRANSMISSION_REFERENCE(710, "%s"),

    VEHICLE_SET_YEAR_NOT_FOUND_BY_ID(800, "%s"),
    VEHICLE_YEAR_OF_MANUFACTURE_NOT_FOUND_BY_ID(801, "%s"),
    INVALID_VEHICLE_YEAR_OF_MANUFACTURE_REFERENCE(802, "%s"),

    UPLOAD_VEHICLE_SET_FILE(900, "%s")
    ;


    private Integer code;
    private String message;
}
